---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox
    tag: "1.30"

outputs:
  - name: status

run:
  path: sh
  dir: status
  args:
  - -exc
  - |
    # touch ./failed
    exit 1
