---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "3.6"

outputs:
- name: gate

run:
  path: sh
  dir: gate
  args:
  - -exc
  - |
    mkdir -p "./env-staging/app-staging"
    echo "$RANDOM" > "./env-staging/app-staging/$RANDOM"
