---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox
    tag: "1.30"

inputs:
- name: status

run:
  path: sh
  dir: status
  args:
  - -exc
  - |
    ls -la
    [ -f ./failed ] && exit 1 || exit 0
