resource_types:
- name: gate-resource
  type: docker-image
  source:
    repository: meshcloud/gate-resource

gate-source: &gate-source
  git:
    uri: https://rymir:((github_token))@github.com/rymir/gate-resource-example.git
    branch: gates

resources:
  - name: repo
    type: git
    source:
      uri: https://rymir:((github_token))@github.com/rymir/gate-resource-example.git
      branch: master

  - name: a-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: a

  - name: b-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: b

  - name: auto-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: autogate

  - name: tf-plan-app-staging-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: tf-plan-app-staging-gate

jobs:
  - name: tf-plan-app-staging-checksum
    plan:
    - get: repo
    - task: tf-plan-app-staging-checksum
      file: repo/ci/tasks/tf-plan-app-staging-checksum.yml
    - put: tf-plan-app-staging-gate
      params:
        item_file: gate/*

  - name: tf-plan-app-staging
    plan:
    - get: repo
    - get: tf-plan-app-staging-gate
      trigger: true
      version: every
    - task: tf-plan-app-staging
      file: repo/ci/tasks/tf-plan-app-staging.yml

  - name: push-a
    plan:
    - get: repo
    - task: gen
      file: repo/ci/tasks/gen-simple.yml
    - put: a-gate
      params:
        item_file: gen/*

  - name: push-b
    plan:
    - get: repo
    - task: gen
      file: repo/ci/tasks/gen-simple.yml
    - put: b-gate
      params:
        item_file: gen/*

  - name: push-autogate
    plan:
    - get: repo
    - in_parallel:
      - get: a-gate
      - get: b-gate
    - task: gen
      file: repo/ci/tasks/gen-autoclose.yml
    - put: auto-gate
      params:
        item_file: gen/*

  - name: autoclose-autogate
    plan:
      - in_parallel:
        - get: a-gate
          trigger: true
        - get: b-gate
          trigger: true
      - put: auto-gate
        params:
          update_autoclose: true

  - name: echo
    plan:
      - in_parallel:
        - get: repo
        - get: auto-gate
          trigger: true
          version: every
      - task: echo
        file: repo/ci/tasks/echo.yml
